CREATE_TB_HISTORY_CPU_UTIL = 'CREATE TABLE IF NOT EXISTS history_cpu_util(datetime INTEGER, host TEXT, usr REAL,nice REAL,sys REAL,iowait REAL,steal REAL,irq REAL,soft REAL,guest REAL,idle REAL, PRIMARY KEY(datetime, host))'
CREATE_TB_TREND_CPU_UTIL = 'CREATE TABLE IF NOT EXISTS trend_cpu_util(datetime INTEGER, host TEXT, usr REAL,nice REAL,sys REAL,iowait REAL,steal REAL,irq REAL,soft REAL,guest REAL,idle REAL, PRIMARY KEY(datetime, host))'
CREATE_TB_HISTORY_MEM_USE = 'CREATE TABLE IF NOT EXISTS history_mem_usage(datetime INTEGER, host TEXT, kbmemfree REAL,kbmemused REAL,kbbuffers REAL,kbcached REAL,kbcommit REAL, PRIMARY KEY(datetime, host))'
CREATE_TB_TREND_MEM_USE = 'CREATE TABLE IF NOT EXISTS trend_mem_usage(datetime INTEGER, host TEXT, kbmemfree REAL,kbmemused REAL,kbbuffers REAL,kbcached REAL,kbcommit REAL, PRIMARY KEY(datetime, host))'
CREATE_TB_HISTORY_IO = 'CREATE TABLE IF NOT EXISTS history_io(datetime INTEGER, host TEXT, device TEXT,readsec REAL,writesec REAL, PRIMARY KEY(datetime, host, device))'
CREATE_TB_TREND_IO = 'CREATE TABLE IF NOT EXISTS trend_io(datetime INTEGER, host TEXT, device TEXT,readsec REAL,writesec REAL, PRIMARY KEY(datetime, host, device))'

INSERT_TB_HISTORY_CPU_UTIL = 'INSERT INTO history_cpu_util (datetime, host, usr, nice, sys, iowait, steal, irq, soft, guest, idle) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(datetime, host) DO NOTHING'
INSERT_TB_TREND_CPU_UTIL = 'INSERT INTO trend_cpu_util (datetime, host, usr, nice, sys, iowait, steal, irq, soft, guest, idle) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(datetime, host) DO NOTHING'
INSERT_TB_HISTORY_MEM_USE = 'INSERT INTO history_mem_usage (datetime, host, kbmemfree, kbmemused, kbbuffers, kbcached, kbcommit)VALUES (?,?,?,?,?,?,?) ON CONFLICT(datetime, host) DO NOTHING'
INSERT_TB_TREND_MEM_USE = 'INSERT INTO trend_mem_usage (datetime, host, kbmemfree, kbmemused, kbbuffers, kbcached, kbcommit)VALUES (?,?,?,?,?,?,?) ON CONFLICT(datetime, host) DO NOTHING'
INSERT_TB_HISTORY_IO = 'INSERT INTO history_io (datetime, host, device, readsec, writesec) VALUES (?,?,?,?,?) ON CONFLICT(datetime, host, device) DO NOTHING'
INSERT_TB_TREND_IO = 'INSERT INTO trend_io (datetime, host, device, readsec, writesec) VALUES (?,?,?,?,?) ON CONFLICT(datetime, host, device) DO NOTHING'

SELECT_HOST_LIST = 'SELECT DISTINCT host FROM history_cpu_util ORDER BY host ASC'
SELECT_IO_DEVICE_LIST = 'SELECT DISTINCT device FROM history_io WHERE host = ? ORDER BY device ASC'

SELECT_HISTORY_CPU_UTIL_TIMEBLOCK = 'SELECT * FROM history_cpu_util WHERE host = ? AND datetime BETWEEN ? AND ?'
SELECT_TREND_CPU_UTIL_TIMEBLOCK = 'SELECT * FROM trend_cpu_util WHERE host = ? AND datetime BETWEEN ? AND ?'
SELECT_HISTORY_MEM_USE_TIMEBLOCK = 'SELECT * FROM history_mem_usage WHERE host = ? AND datetime BETWEEN ? AND ?'
SELECT_TREND_MEM_USE_TIMEBLOCK = 'SELECT * FROM trend_mem_usage WHERE host = ? AND datetime BETWEEN ? AND ?'
SELECT_HISTORY_IO_TIMEBLOCK = 'SELECT * FROM history_io WHERE host = ? AND device = ? AND datetime BETWEEN ? AND ?'
SELECT_TREND_IO_TIMEBLOCK = 'SELECT * FROM trend_io WHERE host = ? AND device = ? AND datetime BETWEEN ? AND ?'

GET_DATETIME_CPU_HISTORY_START = 'SELECT datetime FROM history_cpu_util WHERE host = ? ORDER BY datetime ASC LIMIT 1'
GET_DATETIME_MEM_HISTORY_START = 'SELECT datetime FROM history_mem_usage WHERE host = ? ORDER BY datetime ASC LIMIT 1'
GET_DATETIME_IO_HISTORY_START = 'SELECT datetime FROM history_io WHERE host = ? AND device = ? ORDER BY datetime ASC LIMIT 1'
GET_DATETIME_CPU_HISTORY_END = 'SELECT datetime FROM history_cpu_util WHERE host = ? ORDER BY datetime DESC LIMIT 1'
GET_DATETIME_MEM_HISTORY_END = 'SELECT datetime FROM history_mem_usage WHERE host = ? ORDER BY datetime DESC LIMIT 1'
GET_DATETIME_IO_HISTORY_END = 'SELECT datetime FROM history_io WHERE host = ? AND device = ? ORDER BY datetime DESC LIMIT 1'